=== folio-org/mod-audit/ramls/schemas/external/user.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "User Schema",
  "description": "A user",
  "type": "object",
  "properties": {
    "username": {
      "description": "A unique name belonging to a user. Typically used for login",
      "type": "string"
    },
    "id": {
      "description" : "A globally unique (UUID) identifier for the user",
      "type": "string"
    },
    "externalSystemId": {
      "description": "An ID that corresponds to an external authority",
      "type": "string"
    },
    "barcode": {
      "description": "The library barcode for this user",
      "type": "string"
    },
    "active": {
      "description": "A flag to determine if a user can log in, take out loans, etc.",
      "type": "boolean"
    },
    "type": {
      "description": "The class of user",
      "type": "string"
    },
    "patronGroup": {
      "description": "A UUID corresponding to the group the user belongs to",
      "type": "string"
    },
    "departments": {
      "description": "A UUIDs corresponding to the departments the user belongs to",
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "$ref": "../../raml-util/schemas/uuid.schema"
      }
    },
    "meta": {
      "description": "Deprecated",
      "type": "object"
    },
    "proxyFor": {
      "description" : "Deprecated",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "personal": {
      "description": "Personal information about the user",
      "type": "object",
      "properties": {
        "lastName": {
          "description": "The user's surname",
          "type": "string"
        },
        "firstName": {
          "description": "The user's given name",
          "type": "string"
        },
        "middleName": {
          "description": "The user's middle name (if any)",
          "type": "string"
        },
        "preferredFirstName": {
          "description": "The user's preferred name",
          "type": "string"
        },
        "email": {
          "description": "The user's email address",
          "type": "string"
        },
        "phone": {
          "description": "The user's primary phone number",
          "type": "string"
        },
        "mobilePhone": {
          "description": "The user's mobile phone number",
          "type": "string"
        },
        "dateOfBirth": {
          "type": "string",
          "description": "The user's birth date",
          "format": "date-time"
        },
        "addresses": {
          "description": "Physical addresses associated with the user",
          "type": "array",
          "minItems": 0,
          "items": {
            "type": "object",
            "properties": {
              "id": {
                "description": "A unique id for this address",
                "type": "string"
              },
              "countryId": {
                "description": "The country code for this address",
                "type": "string"
              },
              "addressLine1": {
                "description": "Address, Line 1",
                "type": "string"
              },
              "addressLine2": {
                "description": "Address, Line 2",
                "type": "string"
              },
              "city": {
                "description": "City name",
                "type": "string"
              },
              "region": {
                "description": "Region",
                "type": "string"
              },
              "postalCode": {
                "description": "Postal Code",
                "type": "string"
              },
              "addressTypeId": {
                "description": "A UUID that corresponds with an address type object",
                "type": "string"
              },
              "primaryAddress": {
                "description": "Is this the user's primary address?",
                "type": "boolean"
              }
            },
            "additionalProperties": true
          }
        },
        "preferredContactTypeId": {
          "description": "Id of user's preferred contact type",
          "type": "string"
        },
        "pronouns": {
          "description": "The user's pronouns",
          "type": "string",
          "maxLength": 300
        },
        "profilePictureLink": {
          "description": "Link to the profile picture, or only the id of the /users/profile-picture entry",
          "type": "string",
          "format": "uri"
        }
      },
      "additionalProperties": true,
      "required": [
        "lastName"
      ]
    },
    "enrollmentDate": {
      "description": "The date in which the user joined the organization",
      "type": "string",
      "format": "date-time"
    },
    "expirationDate": {
      "description": "The date for when the user becomes inactive",
      "type": "string",
      "format": "date-time"
    },
    "preferredEmailCommunication": {
      "description": "Preferred email communication types",
      "type": "array",
      "items": {
        "type": "string",
        "enum": ["Support", "Programs", "Services"]
      },
      "maxItems": 3,
      "uniqueItems": true
    },
    "createdDate": {
      "description": "Deprecated",
      "type": "string",
      "format": "date-time"
    },
    "updatedDate": {
      "description": "Deprecated",
      "type": "string",
      "format": "date-time"
    },
    "metadata": {
      "type": "object",
      "$ref": "../../raml-util/schemas/metadata.schema"
    },
    "tags": {
      "type": "object",
      "$ref": "../../raml-util/schemas/tags.schema"
    },
    "customFields" : {
      "description": "Object that contains custom field",
      "type": "object",
      "additionalProperties": true
    }
  },
  "additionalProperties": true
}

=== folio-org/mod-audit/mod-audit-server/src/test/resources/mocks/user_sunny.json
{
  "username": "sunny",
  "id": "2a81b279-d459-4022-82f6-69a569d196b9",
  "barcode": "631888472578232",
  "active": true,
  "type": "patron",
  "patronGroup": "503a81cd-6c26-400f-b620-14c08943697c",
  "departments": [],
  "proxyFor": [],
  "personal": {
    "lastName": "Bernhard",
    "firstName": "Cordell",
    "middleName": "Mafalda",
    "email": "nash@hansen-koepp-and-prohaska.gt",
    "phone": "(675)279-7737 x58358",
    "mobilePhone": "1-658-739-5448 x619",
    "dateOfBirth": "2008-02-20T00:00:00.000+00:00",
    "addresses": [
      {
        "countryId": "US",
        "addressLine1": "64292 Salvatore Trafficway #413",
        "city": "Demopolis",
        "region": "AR",
        "postalCode": "27791",
        "addressTypeId": "1c4b225f-f669-4e9b-afcd-ebc0e273a34e",
        "primaryAddress": true
      }
    ],
    "preferredContactTypeId": "002"
  },
  "enrollmentDate": "2017-12-01T00:00:00.000+00:00",
  "expirationDate": "2020-12-20T00:00:00.000+00:00",
  "createdDate": "2020-11-02T11:01:30.272+00:00",
  "updatedDate": "2020-11-02T11:01:30.272+00:00",
  "metadata": {
    "createdDate": "2020-11-02T11:01:30.258+00:00",
    "updatedDate": "2020-11-02T11:01:30.258+00:00"
  }
}

=== folio-org/mod-audit/mod-audit-server/src/test/resources/mocks/user_diku.json
{
  "username": "diku_admin",
  "id": "fa96fec8-786f-505b-b55e-e0bb1150d548",
  "active": true,
  "patronGroup": "3684a786-6671-4268-8ed0-9db82ebca60b",
  "departments": [],
  "proxyFor": [],
  "personal": {
    "lastName": "ADMINISTRATOR",
    "firstName": "DIKU",
    "email": "admin@diku.example.org",
    "addresses": []
  },
  "createdDate": "2020-11-01T03:21:31.046+00:00",
  "updatedDate": "2020-11-01T03:21:31.046+00:00",
  "metadata": {
    "createdDate": "2020-11-01T03:19:36.441+00:00",
    "updatedDate": "2020-11-01T03:21:31.042+00:00",
    "updatedByUserId": "fa96fec8-786f-505b-b55e-e0bb1150d548"
  }
}
