=== folio-org/mod-audit/ramls/logRecord.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "description": "Main entity for saving/retrieving log info",
  "properties": {
    "eventId": {
      "description": "Event id",
      "$ref": "common/uuid.json"
    },
    "userBarcode": {
      "description": "User barcode",
      "type": "string"
    },
    "itemBarcode": {
      "description": "Item barcode",
      "type": "string"
    },
    "object": {
      "description": "Logged object",
      "type": "string",
      "enum": [
        "Fee/Fine",
        "Item Block",
        "Loan",
        "Manual Block",
        "Notice",
        "Patron Block",
        "Request"
      ]
    },
    "action": {
      "description": "Action",
      "type": "string",
      "enum": [
        "Age to lost",
        "Anonymize",
        "Billed",
        "Cancelled",
        "Cancelled as error",
        "Changed due date",
        "Check in",
        "Check out",
        "Checked in",
        "Checked out",
        "Checked out through override",
        "Claimed returned",
        "Closed loan",
        "Created",
        "Credited fully",
        "Declared lost",
        "Deleted",
        "Edited",
        "Expired",
        "Marked as missing",
        "Modified",
        "Moved",
        "Paid fully",
        "Paid partially",
        "Patron blocked from requesting",
        "Pickup expired",
        "Queue position reordered",
        "Recall requested",
        "Refunded fully",
        "Refunded partially",
        "Renewed",
        "Renewed through override",
        "Request status changed",
        "Send",
        "Staff information only added",
        "Transferred fully",
        "Transferred partially",
        "Waived fully",
        "Waived partially"
      ]
    },
    "date": {
      "description": "Event date",
      "type": "string",
      "format": "date-time"
    },
    "servicePointId": {
      "description": "Service point id",
      "$ref": "common/uuid.json"
    },
    "source": {
      "description": "Source",
      "type": "string"
    },
    "description": {
      "description": "Description",
      "type": "string"
    },
    "linkToIds": {
      "description": "Additional data for details",
      "type": "object",
      "properties": {
        "userId": {
          "description": "User id",
          "$ref": "common/uuid.json"
        },
        "itemId": {
          "description": "Item id",
          "$ref": "common/uuid.json"
        },
        "loanId": {
          "description": "Loan id",
          "$ref": "common/uuid.json"
        },
        "feeFineId": {
          "description": "Fee/Fine id",
          "$ref": "common/uuid.json"
        },
        "templateId": {
          "description": "Template id",
          "$ref": "common/uuid.json"
        },
        "requestId": {
          "description": "Request id",
          "$ref": "common/uuid.json"
        },
        "noticePolicyId": {
          "description": "Notice Policy id",
          "$ref": "common/uuid.json"
        },
        "instanceId": {
          "description": "Instance id",
          "$ref": "common/uuid.json"
        },
        "holdingId": {
          "description": "Holding id",
          "$ref": "common/uuid.json"
        }
      }
    }
  },
  "additionalProperties": true,
  "required": [
    "eventId"
  ]
}

=== folio-org/mod-audit/src/main/resources/samples/manual_blocks/manual_block.json
{
  "eventId":"4862ffc8-1bee-4cf6-af7e-33799dc4d44e",
  "userBarcode": "1000024158",
  "itemBarcode": "12983766",
  "object": "Manual Block",
  "action": "Deleted",
  "date": "2020-08-12T12:21:21.123",
  "servicePointId": "e7f1db20-3e78-4d74-abcb-cdff7d9e91ea",
  "description": "Manual Block test description"
}

=== folio-org/mod-audit/src/main/resources/samples/patron_blocks/patron_block.json
{
  "eventId":"a6231da4-f6fd-4845-8c5d-9c45a4fd4ae2",
  "userBarcode": "1000024158",
  "itemBarcode": "12983766",
  "object": "Patron Block",
  "action": "Edited",
  "date": "2020-08-12T12:21:21.123",
  "servicePointId": "e7f1db20-3e78-4d74-abcb-cdff7d9e91ea",
  "description": "Manual Block test description"
}

=== folio-org/mod-audit/mod-audit-server/src/main/resources/samples/patron_block.json
{
  "eventId":"a6231da4-f6fd-4845-8c5d-9c45a4fd4ae2",
  "userBarcode": "1000024158",
  "itemBarcode": "12983766",
  "object": "Patron Block",
  "action": "Edited",
  "date": "2020-08-12T12:21:21.123",
  "servicePointId": "7c5abc9f-f3d7-4856-b8d7-6712462ca007",
  "source": "Truesdale, Yanic",
  "description": "Manual Block test description",
  "linkToIds": {
    "userId": "df7f4993-8c14-4a0f-ab63-93975ab01c76"
  }
}

=== folio-org/mod-audit/src/main/resources/samples/item_blocks/item_block.json
{
  "eventId":"0c733b7d-22e4-46a6-8851-bf85c8c8eb5b",
  "userBarcode": "1000024158",
  "itemBarcode": "12983765",
  "object": "Item Block",
  "action": "Created",
  "date": "2020-08-12T12:21:21.123",
  "servicePointId": "e7f1db20-3e78-4d74-abcb-cdff7d9e91ea",
  "description": "Item Block test description"
}

=== folio-org/mod-audit/src/main/resources/samples/fee_fine.json
{
  "eventId":"f97da2d5-efdf-45d8-845f-d67b3bd19658",
  "userBarcode": "1000024158",
  "itemBarcode": "12983765",
  "object": "Fee/Fine",
  "action": "Billed",
  "date": "2020-08-12T12:21:21.123",
  "servicePointId": "e7f1db20-3e78-4d74-abcb-cdff7d9e91ea",
  "description": "Fee/Fine test description"
}

=== folio-org/mod-audit/src/main/resources/samples/notice.json
{
  "eventId":"aa332dbe-7d1c-4d9c-8169-8f94c38c1e78",
  "userBarcode": "1000024158",
  "itemBarcode": "12983766",
  "object": "Notice",
  "action": "Send",
  "date": "2020-08-12T12:21:21.123",
  "servicePointId": "e7f1db20-3e78-4d74-abcb-cdff7d9e91ea",
  "description": "Template: Test template. Triggering event: Test triggering event."
}

=== folio-org/mod-audit/src/main/resources/samples/request.json
{
  "eventId":"3fc0567f-129d-49f8-871c-7a3eedd62f34",
  "userBarcode": "1000024158",
  "itemBarcode": "12983766",
  "object": "Request",
  "action": "Created",
  "date": "2020-08-12T12:21:21.123",
  "servicePointId": "e7f1db20-3e78-4d74-abcb-cdff7d9e91ea",
  "description": "Type: Recall. Pickup service point: Circ 1."
}

=== folio-org/mod-audit/mod-audit-server/src/main/resources/samples/item_block.json
{
  "eventId":"0c733b7d-22e4-46a6-8851-bf85c8c8eb5b",
  "userBarcode": "1000024158",
  "itemBarcode": "12983765",
  "object": "Item Block",
  "action": "Created",
  "date": "2020-08-12T12:21:21.123",
  "servicePointId": "7c5abc9f-f3d7-4856-b8d7-6712462ca007",
  "source": "Truesdale, Yanic",
  "description": "Item Block test description",
  "linkToIds": {
    "userId": "df7f4993-8c14-4a0f-ab63-93975ab01c76"
  }
}
